from distutils.sysconfig import customize_compiler
from re import T
from statistics import mode
from django.db import models

# Create your models here.

class SystemUser(models.Model):
    user_id = models.AutoField(primary_key=True)
    username = models.CharField(max_length=50,null=True,unique=True)
    email_id = models.CharField(max_length=50,unique=True)
    password = models.CharField(max_length=20,null=True)

class ArtworkOrder(models.Model):
    customer_id	= models.AutoField(primary_key=True)
    customer_name = models.CharField(max_length=200,null=True)	
    email_id = models.CharField(max_length=200,null=True)	
    phone_number = models.CharField(max_length=20,null=True)	
    discount_rate = models.FloatField(null=True)
    order_date = models.DateField(null=True)
    approved_date = models.DateField(null=True)
    scheduled_print_date = models.DateField(null=True)	
    total_price	= models.FloatField(null=True)
    apparel_item = models.CharField(max_length=150,null=True)
    event_name = models.CharField(max_length=150,null=True)
    base_color	= models.CharField(max_length=50,null=True)
    theme_name	= models.CharField(max_length=150,null=True)
    max_colors	= models.CharField(max_length=150,null=True)
    art_location_01	= models.CharField(max_length=150,null=True)
    description_01 = models.CharField(max_length=1000,null=True)
    cost_01	= models.IntegerField(null=True)
    employee_01	= models.CharField(max_length=150,null=True)
    complete_date_01 = models.DateField(null=True)
    colors_01 = models.CharField(max_length=150,null=True)
    art_location_02	= models.CharField(max_length=150,blank=True,null=True)
    description_02	= models.CharField(max_length=1000,blank=True,null=True)
    cost_02	= models.IntegerField(blank=True,null=True)
    employee_02	= models.CharField(max_length=150,blank=True,null=True)
    complete_date_02 = models.DateField(blank=True,null=True)
    colors_02 = models.CharField(max_length=150,blank=True,null=True)

class PrintOrder(models.Model):

    customer_id	= models.AutoField(primary_key=True)
    customer_name = models.CharField(max_length=200,null=True)	
    email_id = models.CharField(max_length=200,null=True)	
    phone_number = models.CharField(max_length=20,null=True)	
    order_date = models.DateField(null=True)
    art_date = models.DateField(null=True)
    due_date = models.DateField(null=True)
    setup_charge = models.CharField(null=True)
    deposit = models.CharField(null=True)
    discount = models.CharField(null=True)
    total_cost = models.CharField(null=True)
    apparel_orderdate = models.DateField(null=True)
    film_date = models.DateField(null=True)
    print_date = models.DateField(null=True)
    delivered_date = models.DateField(null=True)
    base_color = models.CharField(null=True)
    vendor_name = models.CharField(null=True)
    xs_number = models.CharField(null=True)
    xs_charge = models.CharField(null=True)
    s_number = models.CharField(null=True)
    s_charge = models.CharField(null=True)
    m_number = models.CharField(null=True)
    m_charge = models.CharField(null=True)
    l_number = models.CharField(null=True)
    l_charge = models.CharField(null=True)
    xl_number = models.CharField(null=True)
    xl_charge = models.CharField(null=True)
    xxl_number = models.CharField(null=True)
    xxl_charge = models.CharField(null=True)
    unitbase_price = models.CharField(null=True)
    color_charge = models.CharField(null=True)
    blank_price = models.CharField(null=True)
    location_size = models.CharField(null=True)
    color_change = models.CharField(null=True)
    color_list = models.CharField(null=True)
    final_cost = models.CharField(null=True)

class ProjectCostAnalysis(models.Model):
    project_id = models.CharField(null=True)
    project_name = models.CharField(null=True)
    event_name = models.CharField(null=True)
    item_name = models.CharField(null=True)
    customize_name = models.CharField(null=True)
    phone_number = models.CharField(null=True)
    mc_item_01 = models.CharField(null=True)
    mc_unitcost_01 = models.CharField(null=True)
    mc_pricecharge_01 = models.CharField(null = True)
    mc_units_01 = models.CharField(null=True)
    mc_cost_01 = models.CharField(null=True)
    mc_revenue_01 = models.CharField(null=True)
    mc_item_02 = models.CharField(null=True)
    mc_unitcost_02 = models.CharField(null=True)
    mc_pricecharge_02 = models.CharField(null=True)
    mc_units_02 = models.CharField(null=True)
    mc_cost_02 = models.CharField(null=True)
    mc_revenue_02 = models.CharField(null=True)
    totalcost_01 = models.CharField(null=True)
    totalrevenue_01 = models.CharField(null=True)
    lc_item_01 = models.CharField(null=True)
    lc_unitcost_01 = models.CharField(null=True)
    lc_pricecharge_01 = models.CharField(null=True)
    lc_units_01 = models.CharField(null=True)
    lc_cost_01 = models.CharField(null=True)
    lc_revenue_01 = models.CharField(null=True)
    lc_item_02 = models.CharField(null=True)
    lc_unitcost_02 = models.CharField(null=True)
    lc_pricecharge_02 = models.CharField(null=True)
    lc_units_02 = models.CharField(null=True)
    lc_cost_02 = models.CharField(null=True)
    lc_rvenue_02 = models.CharField(null=True)
    totalrevenue_02 = models.CharField(null=True)
    material_charge = models.CharField(null = True)
    artwork_fees = models.CharField(null=True)
    fixed_charges = models.CharField(null=True)
    total_discounts = models.CharField(null=True)
    net_profits = models.CharField(null=True)