# Generated by Django 3.0.5 on 2022-04-16 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cerulean', '0003_auto_20220415_1932'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='SystemUser',
        ),
    ]
