# Generated by Django 3.0.5 on 2022-04-17 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerulean', '0004_auto_20220416_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtworkOrder',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=200, null=True)),
                ('email_id', models.CharField(max_length=200, null=True)),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('discount_rate', models.FloatField(null=True)),
                ('order_date', models.DateField(null=True)),
                ('approved_date', models.DateField(null=True)),
                ('scheduled_print_date', models.DateField(null=True)),
                ('total_price', models.FloatField(null=True)),
                ('apparel_item', models.CharField(max_length=150, null=True)),
                ('event_name', models.CharField(max_length=150, null=True)),
                ('base_color', models.CharField(max_length=50, null=True)),
                ('theme_name', models.CharField(max_length=150, null=True)),
                ('max_colors', models.CharField(max_length=150, null=True)),
                ('art_location_01', models.CharField(max_length=150, null=True)),
                ('description_01', models.CharField(max_length=1000, null=True)),
                ('cost_01', models.IntegerField(null=True)),
                ('employee_01', models.CharField(max_length=150, null=True)),
                ('complete_date_01', models.DateField(null=True)),
                ('colors_01', models.CharField(max_length=150, null=True)),
                ('art_location_02', models.CharField(max_length=150, null=True)),
                ('description_02', models.CharField(max_length=1000, null=True)),
                ('cost_02', models.IntegerField(null=True)),
                ('employee_02', models.CharField(max_length=150, null=True)),
                ('complete_date_02', models.DateField(null=True)),
                ('colors_02', models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
