# Generated by Django 3.0.5 on 2022-04-17 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerulean', '0005_artworkorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artworkorder',
            name='art_location_02',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='artworkorder',
            name='colors_02',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='artworkorder',
            name='complete_date_02',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='artworkorder',
            name='cost_02',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='artworkorder',
            name='description_02',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='artworkorder',
            name='employee_02',
            field=models.CharField(max_length=150),
        ),
    ]
