# Generated by Django 3.0.5 on 2022-04-17 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerulean', '0006_auto_20220417_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artworkorder',
            name='art_location_02',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='artworkorder',
            name='colors_02',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='artworkorder',
            name='complete_date_02',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='artworkorder',
            name='cost_02',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='artworkorder',
            name='description_02',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='artworkorder',
            name='employee_02',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
