# Generated by Django 4.0 on 2022-04-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerulean', '0008_employeeworkdetails_printorder_projectcostanalysis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeworkdetails',
            name='work_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
