# Generated by Django 4.0 on 2022-04-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerulean', '0010_employeeworkdetails_art_item_01'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeworkdetails',
            name='end_time_01',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeeworkdetails',
            name='task_01',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
