# Generated by Django 4.0 on 2022-04-21 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cerulean', '0013_alter_employeeworkdetails_end_time_01_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeworkdetails',
            name='end_time_01',
        ),
        migrations.RemoveField(
            model_name='employeeworkdetails',
            name='end_time_02',
        ),
        migrations.RemoveField(
            model_name='employeeworkdetails',
            name='pd_start_time_01',
        ),
        migrations.RemoveField(
            model_name='employeeworkdetails',
            name='pd_start_time_02',
        ),
    ]
