# Generated by Django 4.0 on 2022-04-21 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerulean', '0015_employeeworkdetails_pd_start_time_01'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeworkdetails',
            name='end_time_01',
            field=models.TimeField(null=True),
        ),
    ]
