# Generated by Django 4.0 on 2022-04-21 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerulean', '0016_employeeworkdetails_end_time_01'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeworkdetails',
            name='end_time_02',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='employeeworkdetails',
            name='pd_start_time_02',
            field=models.TimeField(null=True),
        ),
    ]
