# Generated by Django 4.0 on 2022-04-22 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cerulean', '0019_rename_apparel_orderdate_printorder_apparelorderdate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='printorder',
            old_name='customer_name',
            new_name='customername',
        ),
        migrations.RenameField(
            model_name='printorder',
            old_name='email_id',
            new_name='emailid',
        ),
    ]
