# Generated by Django 4.0 on 2022-04-22 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cerulean', '0020_rename_customer_name_printorder_customername_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='printorder',
            old_name='order_date',
            new_name='orderdate',
        ),
    ]
